- name: Deploy echo-server
  hosts: ubuntu_servers
  become: yes
  vars_prompt:
    - name: dockerhub_username
      prompt: "Enter your Docker Hub username"
      private: no
    - name: dockerhub_password
      prompt: "Enter your Docker Hub password"
      private: yes

  vars:
    app_dir: "/home/{{ ansible_user }}/echo-app"

  tasks:
    - name: Ensure target directory exists
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      become: no

    - name: Copy docker-compose.yml to remote host
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: "{{ app_dir }}/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
      become: no

    - name: Copy nginx.conf to remote host
      ansible.builtin.copy:
        src: nginx.conf
        dest: "{{ app_dir }}/nginx.conf"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
      become: no

    - name: Include docker role to install Docker
      ansible.builtin.include_role:
        name: docker

    - name: Add remote user to the docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Reset ssh connection to allow group changes to take effect
      ansible.builtin.meta: reset_connection

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
      become: no
      retries: 3
      delay: 5
      register: login_result
      until: login_result is success

    - name: Run Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        state: present
        pull: missing
      become: no

    - name: Log out from Docker Hub
      community.docker.docker_login:
        state: absent
      become: no
      ignore_errors: yes
